CREATE TABLE DEV_MEMBER(
ID VARCHAR(50) PRIMARY KEY, 
NAME VARCHAR(50), 
PASSWORD VARCHAR(50),
REGDATE DATE,
EMAIL VARCHAR(50),
PHONENUMBER1 VARCHAR(3),
PHONENUMBER2 VARCHAR(4),
PHONENUMBER3 VARCHAR(4));

CREATE TABLE DEV_BOARD(
ARTICLE_NO INT PRIMARY KEY,
WRITER_ID VARCHAR(50),
WRITER_NAME VARCHAR(50),
TITLE VARCHAR(255),
REGDATE DATE,
MODDATE DATE,
READ_CNT INT,
CONTENT CLOB);